name: makepkg

on: [push]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: make build
    - name: install
      run: make install
    - name: prune
      run: make prune
